config:
  template_dirs:
  - $SPACK_DEPLOY/templates/$SPACK_ROOT_MODULES_TEMPLATES_SUFFIX
  - $SPACK_DEPLOY/templates
  build_stage:
  - $tempdir
  source_cache: $SPACK_DEPLOY/$SPACK_DEPLOY_INSTANCE/cache
  install_tree:
    root: $SPACK_DEPLOY/$SPACK_DEPLOY_INSTANCE/install
  binary_index_root: $SPACK_DEPLOY/$SPACK_DEPLOY_INSTANCE/cache
